### ISSUE TITLE
Extractions should warn users that column category has changed since last run [Chris]

### ISSUE THREAD

**Issue by RoyMudie** [HicServices/RDMP#1025]
**Is your feature request related to a problem? Please describe.**
When running and extraction if a column category has changed since it was last run there is no prompt to inform the user about this.

**Describe the solution you'd like**
Inform/warn the user that the catalogue column category has changed when running extractions checks

**Comment by tznind** [comment]
I think the new warnings take care of this use case

![image](https://user-images.githubusercontent.com/31306100/164451235-9a016c10-7f54-45fe-a222-4a18179878a8.png)
