### ISSUE TITLE
Parameters need spaces after commas - this should not be the case [Sindy]

### ISSUE THREAD

**Issue by RoyMudie** [HicServices/RDMP#1038]
**Describe the bug**
If you create a parameter in the SQL editor it is automatically picked up and the parameter editor window appears.

However, all parameters need a space before them, meaning that sometimes it can be confusing if you have a function like:
myFunction("string thing", @paramWorks,@paramBorken)

The parser that is picking up parameters with a space before them, but not a comma.

**Expected behavior**
This has the intention of meaning that email addresses in strings aren't made into parameters, but commas can't be used in emails - so as well as a white space before an @, it should also allow a comma.

**Comment by tznind** [comment]
This is a FAnsiSql issue and is fixed in https://github.com/HicServices/FAnsiSql/pull/129
