### ISSUE TITLE
Change icon based on process task type in Data Load [Zsolt]

### ISSUE THREAD

**Issue by RoyMudie** [HicServices/RDMP#1044]
**Is your feature request related to a problem? Please describe.**
It can be hard to tell what types of task are part of a load configuration.

**Describe the solution you'd like**
Add icons based on the Process Task Type so that it's easier to see the different types of tasks being done
![image](https://user-images.githubusercontent.com/5470814/163421981-322fa86b-0106-48a4-90f8-c220ab322e9f.png)

**Comment by zzszarka** [comment]
@RoyMudie could you please indicate data load in the title or a label, so I can remember better. Thanks

**Comment by tznind** [comment]
These are the ProcessTaskTypes

```csharp
/// <summary>
/// ProcessTask is to launch an executable file with parameters telling it about the load stage being operated on (servername, database name etc)
/// </summary>
Executable,

/// <summary>
/// ProcessTask is to run an SQL file directly on the server
/// </summary>
SQLFile,

/// <summary>
/// ProcessTask is to instantiate the IAttacher class Type specified in Path and hydrate it's [DemandsInitialization] properties with values matching 
/// ProcessTaskArguments and run it in the specified load stage in an AttacherRuntimeTask wrapper.
/// </summary>
Attacher,

/// <summary>
/// ProcessTask is to instantiate the IDataProvider class Type specified in Path and hydrate it's [DemandsInitialization] properties with values matching 
/// ProcessTaskArguments and run it in the specified load stage in an DataProviderRuntimeTask wrapper.
/// </summary>
DataProvider,

/// <summary>
/// ProcessTask is to instantiate the IMutilateDataTables class Type specified in Path and hydrate it's [DemandsInitialization] properties with values matching 
/// ProcessTaskArguments and run it in the specified load stage in an MutilateDataTablesRuntimeTask wrapper.
/// </summary>
MutilateDataTable
``

Currently SqlFile and Executable both have custom icons while attacher/mutilator and data provider share the 2 cubes.   (see `ProcessTaskStateBasedIconProvider`).  Do you want these 3 distinguished from each other or were you thinking of something bigger with icons for different class types (see the Path property in your tooltip).

**Comment by RoyMudie** [comment]
Lets just do icons for the there missing ProcessTaskTypes - I'll get icons

**Comment by RoyMudie** [comment]
@tznind  - what you think of...

Attacher = famfamfam\attach.png ![image](https://user-images.githubusercontent.com/5470814/164442536-e5f22b23-fff2-436f-af56-97347eb47053.png)

DataProvider = famfamfam\database_go ![image](https://user-images.githubusercontent.com/5470814/164442496-f91dd393-f74a-4065-a3b8-2d17dc6b7549.png)

MutilateDataTable = famfamfam\arrow_switch  ![image](https://user-images.githubusercontent.com/5470814/164442472-bc311031-1acb-4a38-b053-e49fc04cbee7.png)

**Comment by tznind** [comment]
DataProvider puts data into ForLoading so an arrow into a folder or a cloud with an arrow out of it falling down or something
Attachers put data into data tables in RAW so an arrow pointing at a table or database makes more sense
MutilateDataTable should have a table in it so the arrows with a backdrop of a table make sense
