### ISSUE TITLE
Replace "Delete" option with a "change" for AggregateDimensions

### ISSUE THREAD

**Issue by RoyMudie** [HicServices/RDMP#1102]
**Is your feature request related to a problem? Please describe.**
Users can easily delete aggregate dimensions mistakenly.

**Describe the solution you'd like**
Remove the option for delete because it isn't necessary if they can simply "Change" the dimension instead.

**Comment by tznind** [comment]
Add a ProblemProvider for 'this cohort set doesnt have any dimensions'
