### ISSUE TITLE
Adjust what cohort creation wizard creates

### ISSUE THREAD

**Issue by tznind** [HicServices/RDMP#1114]
There are multiple different ways to implement the selections chosen in the wizard.  The wizard lets you make 9 different permutations of datasets.  These are how those could be interpreted (see below).   The second (most versatile) is probably the prefered one but if we go down that route we will have to make the ProblemProvider messages about empty UNION containers or 1 dataset only in the container be an opt in user setting.

## The most correct
Empty = UNION
1 Inclusion = UNION with aggregate
2 Inclusion = UNION/INTERSECT with 2 aggregates
1 Exclusion = EXCEPT -> UNION (empty) + aggregate 
2 Exclusion = EXCEPT -> UNION (empty) + UNION/INTERSECT (with with aggregates)
1 Inclusion + 1 Exclusion = EXCEPT with 2 aggregate
2 Inclusions + 1 Exclusion = EXCEPT -> UNION/INTERSECT (with aggregates) + aggregate
1 Inclusion + 2 Exclusion = EXCEPT -> aggregate + UNION/INTERSECT (with aggregates)
2 Inclusion + 2 Exclusion = EXCEPT -> UNION/INTERSECT (with aggregates) x2

## The most versatile for later adjustments
Empty = UNION
Any Exclusion Criteria = EXCEPT -> UNION/INTERSECT x2
No Exclusion Criteria = EXCEPT -> UNION/INTERSECT x2

**Comment by RoyMudie** [comment]
Closed by #1115
