### ISSUE TITLE
ScintillaNET not loading on new Azure VMs

### ISSUE THREAD

**Issue by tznind** [HicServices/RDMP#1215]
**See bottom for the workaround (install dotnet sdk)**

**Describe the bug**
When creating a new windows VM on azure e.g. 'Windows (Windows Server 2022 Datacenter Azure Edition)' (but also others).  RDMP runs but reports an error when attempting to load any tab with Scintilla editor running in it.

The issue is reproducible with a minimum repro project too:

```
dotnet new winforms -n scint
dotnet add package fernandreu.ScintillaNET --version 4.2.0

#Add to Form1.cs
Controls.Add(new Scintilla() { Dock = DockStyle.Fill});

dotnet publish -r win-x64 --self-contained
```

The error is:

```
CoreCLR Version: 6.0.522.21309
.NET Version: 6.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.Win32Exception (0x80004005): Could not load the Scintilla module at the path 'C:\Users\smi-admin\AppData\Local\Temp\ScintillaNET\4.2.0\x64\SciLexer.dll'.
---> System.ComponentModel.Win32Exception (126): The specified module could not be found.
at ScintillaNET.Scintilla.get_CreateParams()
at System.Windows.Forms.Control..ctor(Boolean autoInstallSyncContext)
at System.Windows.Forms.Control..ctor()
at ScintillaNET.Scintilla..ctor()
at scint.Form1..ctor() in Z:\Repos\scint\Form1.cs:line 10
at scint.Program.Main() in Z:\Repos\scint\Program.cs:line 14
```

**Installing the dotnet SDK 6.0 fixes the problem**.  But given apps are shipping self contained this is a suboptimal workaround.

**Comment by jas88** [comment]
SciLexer depends on the file VCRUNTIME140.dll, which is not an integral part of Windows but comes as part of the Microsoft Visual C++ 2015 Redistributable package. Anything written in Visual C++ 2015 needs that, so _most_ Windows machines already have a copy - but not a fresh clean Windows install.

Rare enough we might be best just catching that Win32Exception and suggesting "check Visual C++ 2015 Redistributable is installed" with the link? (Come to think of it, DCMtk hits exactly the same issue on clean Windows installs, and doesn't give a helpful error message either...) Alternatively we could check the registry key and pop up the download URL if it's missing.

**Comment by tznind** [comment]
Excellent detective work!
