### ISSUE TITLE
Unhandled exception deAnonymiseAgainstCohort

### ISSUE THREAD

**Issue by zzszarka** [HicServices/RDMP#1233]
**Describe the bug**
Clicking "Choose Cohort" in a data import pipeline with DeanonymiseAgainstCohort element cause unhandled exception causing RDMP to shut down
 
**To Reproduce**
1. Create Project Specific Catalogue from File
2. Select file to load, that has a PROCHI column
3. Fill in the rest of the dialogue
4. Click Execute
5. See error
![image](https://user-images.githubusercontent.com/77501138/173611189-a30cbc24-99f9-4bc8-ae27-161d5a9e17a7.png)

**Expected behavior**
Get a dialogue to pick a cohort to de-anonymise against.

**Screenshots**

Pipeline configuration:
![image](https://user-images.githubusercontent.com/77501138/173609478-9b96d65a-8c4f-4acc-8914-a21cbfcc1f20.png)
![image](https://user-images.githubusercontent.com/77501138/173609673-6748378e-c4c5-460d-b5ac-f8a935ab460f.png)
![image](https://user-images.githubusercontent.com/77501138/173609599-a093d322-5856-44e7-b0d8-23bad35ba0e0.png)

**RDMP Version**
v7.0.13

**Error with Stack Trace**
[new 2.txt](https://github.com/HicServices/RDMP/files/8901102/new.2.txt)

```

```

**Comment by tznind** [comment]
I have updated the private repository RdmpExtensions to the latest version of RDMP API:
https://github.com/HicServices/RdmpExtensions/releases/tag/5.0.0

The change however requires an update to the import file use case to support UI elements:
https://github.com/HicServices/RDMP/pull/1235

I do not recommend adding the pipeline until the above PR is merged and released
