### ISSUE TITLE
Sorting in Select Saved Cohort Dialogue is not sorting

### ISSUE THREAD

**Issue by zzszarka** [HicServices/RDMP#1237]
**Describe the bug**
Sorting in Select Saved Cohort Dialogue is not sorting the list

**To Reproduce**
1. Create an Extraction
2. The Select Saved Cohort Dialogue pops up
3. Try to sort by ID or Name
4. The order of the list does not change

**Expected behavior**
The list is sorted by the chosen column in the chosen direction (ascending/descending)

**Screenshots**
![image](https://user-images.githubusercontent.com/77501138/173820271-aa52f9d2-4933-4177-81f2-a48cf7259726.png)

**RDMP Version**
7.0.13

**Additional context**
This may affect other functionality too

**Comment by tznind** [comment]
Sorting in this UI was removed in #1192 and won't be comming back.  Next RDMP release should show the column as disabled (i.e. no sorting chevron).
