### ISSUE TITLE
Available Columns in Edit Catalogue Extraction

### ISSUE THREAD

**Issue by zzszarka** [HicServices/RDMP#1265]
**Is your feature request related to a problem? Please describe.**
When editing the catalogue extraction, I want to look at all available catalogue columns with the different extractibility classes.
The order of the available columns list:

1. Core
2. Project Specific Catalogue a 
3. Project Specific Catalogue b
4. ...
5. ...
6. Project Specific Catalogue x
7. Special Approval
8. Supplemental
9. Internal

The core items are usually at the top, which is ideal, but the other extractibility are at the bottom of a long list of Project specific catalogues, and as the default view is expanded, it takes time to scroll to the bottom of the list.
Also it is unlikely to add a column from a project specific catalogue at this stage.

**Describe the solution you'd like**
Ideally: Show only columns from the currently edited catalogue.
If RDMP must show project specific columns, list them at the bottom, collapsed by default.

**Describe alternatives you've considered**
add a tick list, to select catalogues for which to display available columns.

**Additional context**
![image](https://user-images.githubusercontent.com/77501138/176481118-1c7a66af-2bba-44dd-a5b4-9bf2d3af90f7.png)
suggested:
![image](https://user-images.githubusercontent.com/77501138/176481656-7224376f-ad0a-465e-ad94-b89acd4a6186.png)

**Comment by tznind** [comment]
If you want to see Supplemental items you can type 'Supplemental' into the Search box.

![image](https://user-images.githubusercontent.com/31306100/177278038-40515477-93be-4984-8e7f-b158b559b4b3.png)

**Comment by zzszarka** [comment]
Thank you for the suggestion, but it does not make the task easier, because it means typing instead of scrolling, and if I want to check core again, I would have to type "Core" again.
Is there any problem with my suggestion above?

**Comment by tznind** [comment]
I have added a tickbox that disapears them when you untick it.  Value is persisted in UserSettings so if you restart/reopen UI it's state should be preserved

**Comment by zzszarka** [comment]
Thank you. What is the default setting?

**Comment by tznind** [comment]
> Thank you. What is the default setting?

true (show Project Specific Columns).
