### ISSUE TITLE
Delete extraction does not remove the extraction from the list

### ISSUE THREAD

**Issue by zzszarka** [HicServices/RDMP#1298]
**Describe the bug**
Delete Extraction does not refresh the list of extractions

**To Reproduce**
1. Go to an extraction
2. Right click and select "Delete"
3. Confirm delete
4. Extraction is still there, with error: No catalogues selected for extraction
5. Right-click Project, "Refresh"
6. Extraction is now deleted

**Expected behavior**

**Screenshots**
confirm delete:
![image](https://user-images.githubusercontent.com/77501138/179478581-b90f0408-e5e1-45c8-9d3a-a7916cf3ddfe.png)
extraction not deleted, but catalogues are removed:
![image](https://user-images.githubusercontent.com/77501138/179479014-2e95ac39-ef3b-47ca-9bdb-a1a56319f7ff.png)

**RDMP Version**
7.0.14

**Error with Stack Trace**
```
If applicable, paste the entire stack trace here, leave the triple quotes (```)
```

**Database Engine**
Sql Server, Oracle, MySql or Postgres.

**Additional context**

**Comment by tznind** [comment]
Seems to have already been resolved and not present in 8.x
