### ISSUE TITLE
Running 2+ binaries at once and NLog.config [ZSolt]

### ISSUE THREAD

**Issue by tznind** [HicServices/RDMP#1300]
Question:
How does RDMP handle running 2 instances both logging to same output dir

**Comment by jas88** [comment]
Should work fine on Linux, not sure about the default file sharing mode on Windows so it _could_ hit errors there.

**Comment by tznind** [comment]
Going to close this because I'm pretty sure that its not what is responsible for @zzszarka not being able to find log files.  Most likely its running a different copy of the binary or from a different current directory or something.
