### ISSUE TITLE
When running in CLI iterative command mode typing 'null' for a file arg creates a file named "null"

### ISSUE THREAD

**Issue by tznind** [HicServices/RDMP#1363]
**Describe the bug**

The following command outputs the data to a file called "null" in the current directory (bad)

```
2022-08-15 08:08:22.5304 INFO Command Completed . 
Enter Command (or 'exit')
Command
ViewData
Value needed for obj (IMapsDirectlyToDatabaseTable)
TableInfo:*launch*US_StudyTable*
Value needed for viewType (ViewType)
TOP_100
Enter File for 'toFile'
null
Enter value for Value needed for useCache (Boolean)
Value needed for useCache (Boolean)(Y/n)
n
```

**Comment by jas88** [comment]
Do we want to special-case "null" so the output gets written to `/dev/null` (or Windows equivalent) for this?

**Comment by tznind** [comment]
I need to look into this a bit.  This code detects the user providing 'null' on command line.  But if you run rdmp just as `./rdmp cmd` (i.e. without entering a command) then it enters an 'interactive loop' that prompts for command (then arguments).  See above for example.  It ends when user enters "exit".

The logic is working as intended for the full command e.g.

`./rdmp ViewData TableInfo:*launch*US_StudyTable* TOP_100 null false`

That code is like this:

https://github.com/HicServices/RDMP/blob/0f9bb6859672db1016210082af4d932ecb0e2ea2/Rdmp.Core/CommandLine/Interactive/Picking/CommandLineObjectPickerArgumentValue.cs#L59-L64

But I suspect in 'interactive mode' it uses `IBasicActivateItems` directly e.g. `FileInfo SelectFile(string prompt)` which isn't correctly detecting that the user typed null in.
