### ISSUE TITLE
Support for Logging to alt DBMS

### ISSUE THREAD

**Issue by tznind** [HicServices/RDMP#1378]
**Is your feature request related to a problem? Please describe.**
Create FAnsi style schemas for Logging patcher

**Comment by jas88** [comment]
How difficult would an option to log to file be?

**Comment by tznind** [comment]
> How difficult would an option to log to file be?

It is a hierarchical logging structure with various activities predefined and a fair bit of integration to the RDMP client (gui and CLI).  There are commands that interface with it too (e.g. verify task x has been logged recently and that it reported success).

So its called logging but its more like audit.

Logging to MySql seems doable though
