### ISSUE TITLE
Error during patching - RDMP_Cache had status Unreachable

### ISSUE THREAD

**Issue by rkm** [HicServices/RDMP#1492]
**Describe the bug**

```console
$ ./rdmp patch 
2022-11-10 15:55:26.4483 INFO Dotnet Version:6.0.10 . 
2022-11-10 15:55:26.5354 INFO RDMP Version:8.0.6.0 . 
2022-11-10 15:55:45.5508 ERROR Database RDMP_Cache had status Unreachable . 
2022-11-10 15:55:46.0899 INFO Exiting with code -1
```

```console
> cat Databases.yaml 
CatalogueConnectionString: server=...;uid=SA;password=...;database=RDMP_Catalogue;Trust Server Certificate=true;Encrypt=false;
DataExportConnectionString: server=...;uid=SA;password=...;database=RDMP_DataExport;Trust Server Certificate=true;Encrypt=false;
```

**To Reproduce**

Run patch with the settings above.

**Expected behavior**

The patch to succeed.

**Screenshots**

N/A.

**RDMP Version**

v8.0.6.

**Error with Stack Trace**

As above.

**Database Engine**

SQL Server.

**Additional context**

N/A.

**Comment by tznind** [comment]
Try deleting the  the ExternalDatabaseServer called caching

**Comment by rkm** [comment]
Thanks Thomas. How do I remove it as the default cache?

If I try deleting at the moment I see:

![rdmp-cache-delete](https://user-images.githubusercontent.com/5160559/201161581-414f52fb-9654-4b41-b72f-d814bf97f923.PNG)

**Comment by tznind** [comment]
You need to delete it from any `CohortIdentificationConfiguration` that use it as their cache:

![image](https://user-images.githubusercontent.com/31306100/201165168-0790b6b3-0a55-4ef6-89dd-a07386e4742f.png)

_Click Remove_

Then clear the default status 
![image](https://user-images.githubusercontent.com/31306100/201164919-f423d181-0cd4-4f72-9fe2-5581fb70327d.png)

**Comment by rkm** [comment]
That fixed the `patch` command -- thanks Thomas!
