### ISSUE TITLE
dotnet 5.0 plugin structure

### ISSUE THREAD

**Issue by tznind** [HicServices/RDMP#322]
Now that develop has moved to using dotnet 5.0 we need to look again at the plugin structure

Current structure is 

```
lib\net461\ plugins UI dlls
lib\netcoreapp2.2\plugins cli dlls
PluginName.nuspec
```

This could change to:
```
\lib\core
\lib\win    (optional depending on whether plugin has winforms specific features)
PluginName.nuspec
```

The Windows app and CLI would change to both loading from core instead of net461.  Then the UI would also load from ui (if present).

## Advantages

- Cut down size of plugins by half
- Simplify plugin writting
- Avoid current confusing references to specific versions of dotnet core/framework

**Comment by jas88** [comment]
Good plan - maybe "win" rather than "ui" since it's "net5.0-win" as opposed to plain "net5.0"? Or keep versions in there, to make old plugins more obvious and easier to ignore/identify/handle - "net5" and "net5-win"?

**Comment by tznind** [comment]
`win` is a good shout for subdir.  We already have a compatibility spec in the `PluginName.nuspec`.  The plugin needs to list major and minor e.g. `5.0` for version of RDMP dependency.  So as long as we don't jump up to dotnet6 without bumping major or minor we should be good and it means the plugin repo CI doesn't need to be updated again to the new folder/framework.
