### ISSUE TITLE
SupportingDocument url should support UNC file paths

### ISSUE THREAD

**Issue by tznind** [HicServices/RDMP#329]
Reported by Gary

Works

file:///Z:/out/loadme.txt

But if you want to say `\\myserver-bob-fff\myfile.txt` and save it changes it to `file://myserver-bob-fff/myfile.txt` on saving

**Comment by jas88** [comment]
That's the correct conversion of the UNC filename to a file: URL...

**Comment by tznind** [comment]
Ok cool, then need to make it treat that properly in the extraction component (or verify that it does in fact work).  And that the 'Browse' (show me where this file is) buttons work correctly with UNC too.

**Comment by tznind** [comment]
Think this is probably the issue

https://github.com/HicServices/RDMP/blob/90da85895cfbc52a7db51658c452920091d37b5b/Rdmp.Core/Curation/Data/SupportingDocument.cs#L161-L166
