### ISSUE TITLE
Packaging suggestions

### ISSUE THREAD

**Issue by rkm** [HicServices/RDMP#411]
Couple of suggestions for the release packaging:

- Unzipping rdmp-cli.zip spills all the files into the current directory by default. Ideally it should extract files to a named directory
- The release package names don't contain the version string, so it's difficult to tell from the file alone what version is contained
- Provide a checksum file so that users can verify the packages have been downloaded correctly before unzipping
- the `rdmp` cli program doesn't have executable permissions

**Comment by tznind** [comment]
> 
> 
> Couple of suggestions for the release packaging:
> 
>     * Unzipping rdmp-cli.zip spills all the files into the current directory by default. Ideally it should extract files to a named directory

Doesn't this depend on the unzipping tool? normally a zip file doesn't have a top level folder in the archive. 

> 
>     * The release package names don't contain the version string, so it's difficult to tell from the file alone what version is contained
> 
>     * Provide a checksum file so that users can verify the packages have been downloaded correctly before unzipping
> 
>     * the `rdmp` cli program doesn't have executable permissions

These are great ideas.  I think we would need to change to `.tar` or `.tar.gz` in order for the +x attribute to be retained.  I think zip archives do not retain this info.

**Comment by jas88** [comment]
For tar files it's normal to have a single parent directory included - just having a bunch of files included directly is called a "tarbomb" - but for zips as you say tools often insert this for you automatically (as with the MacOS one) or optionally (7zip on Windows).

I'll take a look at the packaging this week - should be able to address all these points pretty quickly.

**Comment by tznind** [comment]
When implementing these changes make sure to also update the docs here:

- https://github.com/HicServices/RDMP/blob/develop/Documentation/CodeTutorials/FAQ.md#updating-the-cli
