### ISSUE TITLE
Rounding confuses people

### ISSUE THREAD

**Issue by jas88** [HicServices/RDMP#544]
**Is your feature request related to a problem? Please describe.**

People wrongly assume numbers are decimal even when they're really using binary float types, and don't understand that 0.1 is not an exact value. To make matters worse, Microsoft SSMS apparently rounds data in what someone presumably thought was a "smart" way, so that raw values of 1.68000000000002 and 1.6799999999999999 get rounded to 1.68 as if that had been stored all along.

**Describe the solution you'd like**

Some users expect the "smart" unsolicited rounding of values for display and export rather than getting the actual values. If they really want vaseline on toast, sometimes we should deliver.

**Describe alternatives you've considered**

In an ideal world, we'd educate the user better. More pragmatically, a smart-ish rounding _option_ might be popular with those users. Just casting numerical values to string types seems to get MSSQL to do this dirty work for us, which might be an option.

**Additional context**

<img width="526" alt="Screenshot 2021-09-21 at 11 55 14 AM" src="https://user-images.githubusercontent.com/9466/134214265-7cb96323-f857-4439-8011-85a64b894a5c.png">

`select str(1.68,25,16), cast(1.68 as float),cast(1.68 as nvarchar);`

1.6799999999999999 | 1.68 | 1.68

**Comment by tznind** [comment]
This is probably best handled in `CSVOutputFormat` with last minute rounding when writing out as text.

As far as behaviour injection goes it can be an `int?` property (e.g. `MaxDecimalPlaces`) of `ExecuteDatasetExtractionFlatFileDestination`.  But also used is `ExtractTableVerbatim` so a `UserSettings` value would make sense .  

Basically use the user setting value if it is not null unless there is a setting configured in the destination in which case use that.
