### ISSUE TITLE
Build warning caused by NuDoc 0.5.0

### ISSUE THREAD

**Issue by rkm** [HicServices/RDMP#6]
👋
The `HIC.RDMP.Plugin` project (and projects which depend on it) has a dependency on NuDoc/NuDoq 0.5.0 which produces the following warning on builds: "Warning NU1602 NuDoc 0.5.0 does not provide an inclusive lower bound for dependency NuDoq. An approximate best match of NuDoq 1.2.5 was resolved". It also appears the package hasn't been updated since 2015, and does not fully support .NET Core, so maybe it's use could be reviewed? Thanks.

**Comment by tznind** [comment]
Accepted as RDMPDEV-1537 : Drop dependency on NuDoq

**Comment by tznind** [comment]
Fixed in develop, waiting for next release (will be in 3.1.1)
