### ISSUE TITLE
Project Summary user interface does not show list of cohorts when one or more Cohort Sources are unreachable

### ISSUE THREAD

**Issue by tznind** [HicServices/RDMP#622]
## Background

A Cohort is a list of identifiers.  Each list in RDMP has a single 'project number' associated with it.  This value is stored in the Cohort Database.  An RDMP deployment can have multiple cohort databases (e.g. for different forms of anonymisation or different cohort private identifier formats).  Some users may be unable to access all of the cohort databases (which is fine).

ProjectUI shows all extraction configurations and all cohorts (whether they are in use or archival etc).  

## Problem
Since ProjectNumber is in the Cohort database and not RDMP it is not possible to exhaustively detect all cohorts used by a Project when the user is missing access permissions to that database.

What should happen is that the cohorts they *do* have accsess to should be shown and the rest should be ignored (when found to be unreachable).

What does happen is that the ProjectUI gives up and reports blank screen with unobtrusive global error in log:
![image](https://user-images.githubusercontent.com/31306100/139670767-c6380e08-908f-4da3-9044-cc5282747aea.png)

**Comment by RoyMudie** [comment]
From the project view -> double click a project -> get this view and it stalls trying to load the summary:
![image](https://user-images.githubusercontent.com/5470814/149494529-f80658aa-e63f-44b3-9b28-f9ebea7347ad.png)
