### ISSUE TITLE
Support creating backup trigger index and legacy view (sql server only) with long timeout [Zsolt]

### ISSUE THREAD

**Issue by tznind** [HicServices/RDMP#623]
**Is your feature request related to a problem? Please describe.**
When attempting to create the `_Archive` table index and `_Legacy` table valued function on a table that has millions of rows the timeout can get hit. 

Add an ability to inject a higher timeout into this process.  Possibly via a user setting or an override to the command or something

**Comment by RoyMudie** [comment]
Can be set in the command line with:
RDMP cmd setusersetting
