### ISSUE TITLE
cohort configuration - highlight in red root container when "except" and only contain 1 child [Magalie]

### ISSUE THREAD

**Issue by RoyMudie** [HicServices/RDMP#681]
Any container highlights in red when its status is an Except and there is only 1 child. This rule doesn't apply to root container but Root container could still be an Except 

![image](https://user-images.githubusercontent.com/5470814/143015257-dc443fc9-074b-4e04-ba89-5672968b4522.png)

Roy Mudie added a comment - Yesterday 10:46 AM
Comments from DLS team:
Unions should be the default container that accepts 1 or more elements
Excepts and Intersect should allow 2 or more elements and fail otherwise

Note: because existing cohorts are built with intersects, with only one element, this will mean that CICs will need updated. 

https://jira.hic.dundee.ac.uk/browse/RDMPSUP-157

**Comment by RoyMudie** [comment]
Found `\RDMP\Rdmp.Core\Curation\Data\Cohort\CohortAggregateContainer.cs` -> `IsRootContainer()` but this isn't referenced by `\RDMP\Rdmp.Core\Providers\CatalogueProblemProvider.cs` -> `DescribeProblem(CohortAggregateContainer container)`

Instead there's a ID check:
``` 
//if it's a root container don't check
if (_childProvider.AllCohortIdentificationConfigurations.Any(c =>
  c.RootCohortAggregateContainer_ID == container.ID))
  return null;```

**Comment by tznind** [comment]
> Found `\RDMP\Rdmp.Core\Curation\Data\Cohort\CohortAggregateContainer.cs` -> `IsRootContainer()` but this isn't referenced

This is for performance `_childProvider.AllCohortIdentificationConfigurations` is a collection in memory so it is faster to query than `IsRootContainer` which involves a round trip to the database.

We could add an overload for `IsRootContainer` that takes an `ICoreChildProvider` if you want? that would improve API user experience.

**Comment by RoyMudie** [comment]
Further work on the development of default containers will be carried out in ticket #682
