### ISSUE TITLE
Buffer long data extractions to allow restarting at faliure point [Magalie]

### ISSUE THREAD

**Issue by RoyMudie** [HicServices/RDMP#683]
It occurs very frequently that an extraction fails after many hours running due to various reasons which could be solved on the go and allow the extraction to finalise correctly. Most of the time  the reason is due to timeout / space disk / metadata error / wrong pipeline configuration and nothing can prevent this until an extract reach the point of failure after hours running.
The only options remaining ane then 
- run manually in SQL (but lose metadata which can't be generated separately or before the data extraction)
- Try again in RDMP and hope for the best. 

We face more and more big data extractions - and this is not sustainable as RDMP failures during extraction, delay a lot of projects releases. It can take a week just to extract all data for one single project.

If RDMP could memorise the latest point of execution are "pause" it until manual intervention resolve the issue - it would definitely help us and reduce significant delays and frustrations 

https://jira.hic.dundee.ac.uk/browse/RDMPSUP-156

**Comment by tznind** [comment]
Batch by date:

1. User picks date field
2. User enters start and end date

RDMP:
1. Detects that it is first run
    1. Truncates endpoint file
    2. Runs pipeline for 1 year/month/day
2. Runs again 
    1. Detects progress has started but not ended
    2. Runs pipeline for 1 year/month/day
    3. Writes to destination in Append mode

**Comment by tznind** [comment]
Things that could cause issues when using batch execution pipeline:

1. Loading data during extraction
2. Changing the Catalogue time periodicity column
3. Middle components that expect data they see to be the whole picture or do truncate/recreate stuff independently on their own.
4. Running in batch mode then cancelling after 3 batches then running in normal mode then running in batch again

**Comment by tznind** [comment]
None of these systems will work correctly when running pipeline multiple times:

https://github.com/HicServices/RDMP/blob/921454e8ef132fe576858b2457ce6c632e63be02/Rdmp.Core/DataExport/DataExtraction/Pipeline/Sources/ExecuteDatasetExtractionSource.cs#L52-L57

**Comment by tznind** [comment]
This is too complicated for a pipeline component to handle.  It requires a core rewrite starting with `ExtractionQueryBuilder`.  See the draft PR for progress
