### ISSUE TITLE
Configure what columns are selected from lookup [Zsolt]

### ISSUE THREAD

**Issue by RoyMudie** [HicServices/RDMP#692]
At the moment RDMP extracts all columns from lookup tables.
In particular hic_dataLoadRunID and hic_validFrom would not be extracted usually.
Please enable the user to select what columns are selected from a lookup. 

https://jira.hic.dundee.ac.uk/browse/RDMPSUP-140

**Comment by tznind** [comment]
> In particular hic_dataLoadRunID and hic_validFrom would not be extracted usually.

The [ColumnDropper](https://github.com/HicServices/RDMP/blob/develop/Rdmp.Core/DataLoad/Modules/DataFlowOperations/ColumnDropper.cs) can be used to define system wide rules about not extracting given columns (i.e. dropping them from the dataset being extracted).

> Please enable the user to select what columns are selected from a lookup.

A `SupportingSQL`  object (shown in the picture) allows selecting any columns you want from an arbitrary table as a 'lookup table'.  If this is crashing consistently with the screenshot message then we need to look into that.  It looks very low level error.

**Comment by tznind** [comment]
A `Lookup` object itself is different and is used in the creation of code/description relationships. 


Is this about whether the lookups appear in the the word metadata report e.g. here we can see the full Lookup table is getting examined for the Word Metadata Report:

![image](https://user-images.githubusercontent.com/31306100/143444177-de5937f0-e292-4256-b7d4-e91875181640.png)

**Comment by tznind** [comment]
Ok so to confirm:
- You can extract whatever you want from a `SupportingSql`

For `Lookup` objects we can make the following changes
- Only write into metadata documents the code and description column(s) of the Lookup
- Only extract the code and description column(s) of the Lookup if it is included in an ExtractionConfiguration as a bundled lookup

Bear in mind that a Lookup can have multiple of each pk and desc column.  For example where you have a test code AB1 that maps to 2 different tests - 1 in Tayside and 1 in Fife (so the join is TestCode+Healthboard => DrugDesc).
