### ISSUE TITLE
New feature: see all Catalogue PKs [Zsolt]

### ISSUE THREAD

**Issue by RoyMudie** [HicServices/RDMP#705]
Currently if the user want to see Catalogue Extraction PKs on a catalogue, you have to open every catalogue item.
Please enable an easier way to see all Catalogue PKs at one look.
Ideally: show the list in "Edit Catalogue" and an icon next to each catalogue item. 

Roy Mudie added a comment - Yesterday 9:39 AM
Note from [~chall] - there is a difference between a DB PK and RDMP PK.

screenshot-1.png is showing the RDMP PK and is the only way of accessing that information.
Roy Mudie added a comment - Yesterday 9:43 AM
Possible solutions:
Key icon in lower left (similar to "tables" view) (screenshot-2.png)
"Catalogue Items -> Primary Keys" folder that lists all primary key columns

![image](https://user-images.githubusercontent.com/5470814/143020156-f8f20c44-3d1c-4fcf-a161-cddd47013782.png)

![image](https://user-images.githubusercontent.com/5470814/143020201-d9ab1ccf-edf4-4693-b508-9a1454b81a08.png)

**Comment by tznind** [comment]
On a `ColumnInfo` the IsPrimaryKey setting indicates that the the lasts time RDMP synced with the database the column was part of the primary key in the DBMS
On a `CatalogueItem` the IsPrimaryKey setting indicates that **when extracting this dataset** the column forms part/all of the primary key on the records produced

For example if you only extract CHI+Date field from a table then the extraction primary key might be CHI+Date while in the underlying table it is CHI+Date+DoctorsNotes
