### ISSUE TITLE
Update UI icons by fixing obvious errors

### ISSUE THREAD

**Issue by RoyMudie** [HicServices/RDMP#712]
**Is your feature request related to a problem? Please describe.**
Some icons have hard readability or obvious errors (e.g. smiley faces are hard to understand and "CatalogueItem.png" has a black corner rather than transparent)

**Describe the solution you'd like**
Move to Material UI icons https://google.github.io/material-design-icons/

Browse the library here: https://fonts.google.com/icons?selected=Material+Icons

The amount of icons in RDMP is extensive and relies of a variety of methods of displaying the icons and overlays. In addition, some icons have been hand made to combine "folders" with components, so care should be taken to consider these various ways of viewing the icons when making them.

Easy first candidates include:

- [x] "\RDMP\Rdmp.Core\Icons\CatalogueItem.png" and "catalogueItemsNode.png" which have a black corner

- [x] Grey, green, yellow and red smiley faces (small version in here: \RDMP\Rdmp.Core\Icons, large version controlled by \RDMP\Rdmp.UI\ChecksUI\ChecksUI.cs) should be replaced with more meaninful icons.

- [x] \RDMP\Rdmp.Core\Icons\Overlays\Cloud.png is hard to see

- [ ] Anything else obvious...

**Comment by tznind** [comment]
Great work.  Just tried it out.  Looking good but did notice we still have a few differing icons that mean 'bad'

![image](https://user-images.githubusercontent.com/31306100/143195451-87e83124-027a-418b-93bc-1f8760bac555.png)
