### ISSUE TITLE
ErrorProvider no longer visible with docked controls

### ISSUE THREAD

**Issue by tznind** [HicServices/RDMP#758]
**Describe the bug**
![image](https://user-images.githubusercontent.com/31306100/144425867-3795a9eb-59eb-4b68-afab-7ff88dd8d4b9.png)

See https://stackoverflow.com/questions/25024460/errorprovider-of-the-docked-control

**Comment by tznind** [comment]
I think we could scrap the `BinderWithErrorProviderFactory` subsystem entirely and move this kind of thing into Checks or `ProblemProvider` since its basically just replication.

There is some nice logic about picking up these attributes with reflection but we could roll that into checks

```csharp
if (property.GetCustomAttributes(typeof (UniqueAttribute), true).Any())
	new UniqueRule<T>(_activator, databaseObject, getter, c, dataMember);

if (property.GetCustomAttributes(typeof(NotNullAttribute), true).Any())
	new NotNullRule<T>(_activator, databaseObject, getter, c, dataMember);

if(dataMember.Equals("Name") && databaseObject is INamed)
	new NoBadNamesRule<T>(_activator, databaseObject, getter, c, dataMember);
```

**Comment by RoyMudie** [comment]
I agree that having a combined error provider is probably a good idea. I also think we should be looking at some of the uses of the docked layouts though. I don't think it's the right tool in this instance

**Comment by RoyMudie** [comment]
![image](https://user-images.githubusercontent.com/5470814/144865188-03b5333a-0648-471e-9450-b8d0ff55ccd7.png)
