### ISSUE TITLE
Mousewheel scroll works on pipeline arguments combobox so they can be changed (and saved) without user noticing

### ISSUE THREAD

**Issue by RoyMudie** [HicServices/RDMP#778]
**Describe the bug**
When editing a pipeline component it's possible that you want to scroll the list of arguments but hover over a combobox. This in turn means that when you scroll the mouse wheel the combobox changes value unintentionally.

This is a problem because: 
1. Pipeline argument options are saved automatically
2. There is no feedback to the user that a change has been made
3. There is no way to change the setting back to the old value

This is particularly problematic with larger lists used for column mappings.

**To Reproduce**
1. Edit a pipeline component
2. Scroll over any argument with a combobox
![image](https://user-images.githubusercontent.com/5470814/145005251-73772503-5285-433c-aa6b-1a2f78acc201.png)

**Expected behavior**
The mouse wheel should not change the value unless the combobox is open for editing.

**Comment by tznind** [comment]
Well its a windows feature.  But if you don't like it it i looks like you can disable it using:

```
myComboBox.MouseWheel += (s,e)=> ((HandledMouseEventArgs)e).Handled = true;
```

https://stackoverflow.com/questions/1882993/c-sharp-how-do-i-prevent-mousewheel-scrolling-in-my-combobox

**Comment by RoyMudie** [comment]
Updated to allow the scroll wheel to work while opened:
`cbxValue.MouseWheel += (s, e) => ((HandledMouseEventArgs)e).Handled = !((ComboBox)s).DroppedDown;`
