### ISSUE TITLE
Group context menu items with line seperator (Delete, Rename, Goto)

### ISSUE THREAD

**Issue by tznind** [HicServices/RDMP#782]
![image](https://user-images.githubusercontent.com/31306100/145017355-4aaf0d90-b06c-473b-8d06-bb05295a07b3.png)

**Comment by RoyMudie** [comment]
These should be grouped at the bottom above the "inspection/tree/favourite" options

**Comment by RoyMudie** [comment]
Order should be:
- Disable (to avoid it being next to delete)
- Rename
- Go To...
- Delete
