### ISSUE TITLE
IsProperTransform should be shown with an icon

### ISSUE THREAD

**Issue by tznind** [HicServices/RDMP#818]
It would be nice if ExtractionInformation / CatalogueItem that are transforms were indicated (like how hashes are)

**Comment by RoyMudie** [comment]
![CatalogueItemNotProperTransform](https://user-images.githubusercontent.com/5470814/145565591-0b82039a-ada3-456f-9330-eadd4341d3f6.png)

Thinking it might make sense to just inverse the colours of the icon for now.

Note: "IsProperTransform" is going to be pretty meaningless from a UI point of view, so I suggest something as simple as "User Created" or "Modified" might be a better fit.
