### ISSUE TITLE
Consistent overlays for ExtractionInformation / CatalogueItem icons

### ISSUE THREAD

**Issue by tznind** [HicServices/RDMP#830]
![image](https://user-images.githubusercontent.com/31306100/146181310-ad953ef8-17c5-4037-a6a4-4e847b0e30f4.png)

**Comment by RoyMudie** [comment]
**Normal:**
![image](https://user-images.githubusercontent.com/5470814/146383206-39b176b2-fd80-4285-a6c1-9a35a6e394dc.png)

**Transforms data** (e.g. column is a count of something)
![image](https://user-images.githubusercontent.com/5470814/146383298-a89ad443-1c61-458a-b141-d0c7800b7b0c.png)
![image](https://user-images.githubusercontent.com/5470814/146383320-6fefde62-1c44-49e1-a845-a124cb081054.png)

**Hash on Data Release icon** (note that it has also "transformed" the data at the same time)
![image](https://user-images.githubusercontent.com/5470814/146383473-d5376cca-25ce-423a-8fdf-69ece5776b25.png)

**Is Extraction Identifier**
![image](https://user-images.githubusercontent.com/5470814/146383525-888f792e-5713-48f4-ac05-681ecf2983e8.png)

**Is Extraction Primary Key**
![image](https://user-images.githubusercontent.com/5470814/146383626-222e365e-72b2-4f79-a7aa-ac83a3cd5b14.png)
