### ISSUE TITLE
Tooltip for ExtractionFilter throws NotSupportedException exception

### ISSUE THREAD

**Issue by RoyMudie** [HicServices/RDMP#843]
**Describe the bug**
Hover over a ExtractionFilter and you'll receive the following error:

`
System.NotSupportedException
  HResult=0x80131515
  Message=Specified method is not supported.
  Source=Rdmp.Core
  StackTrace:
   at Rdmp.Core.Curation.Data.ExtractionFilter.get_FilterContainer_ID() in C:\GitHub\HIC\RDMP\Rdmp.Core\Curation\Data\ExtractionFilter.cs:line 67
`

**Comment by tznind** [comment]
We should unit test that `GetSummary()` works on all objects.  Theres already a test that loops all `WhenIHaveA<T>()`  DatabaseEntity Types and invokes them all returning instances.  So should be pretty easy to add this new test case.
