### ISSUE TITLE
Updates for RDMP should let the user know if there's a database change involved with a patch

### ISSUE THREAD

**Issue by RoyMudie** [HicServices/RDMP#856]
**Is your feature request related to a problem? Please describe.**
Currently it's not obvious if an RDMP update will require a database patch. Consider giving the user a notification before doing the update if a database patch is required (e.g. include in version number)

**Comment by tznind** [comment]
I think the easiest way to handle this is by including database patches in the changelog as the first entry in the list (see below).

That would make it apparent both when directly updating through the windows client and when an administrator is handling that process (e.g. with an update script or in an offline environment).

The RDMP CLI has a command for applying patches and that does not fail if there are no patches to apply so should be pretty easy to create a managed process for central updating.

![image](https://user-images.githubusercontent.com/31306100/148531683-e319ce49-8ce1-4ed2-a2b8-9da6e0ae6d88.png)

If you are happy with that solution we can probably close this issue unless you want it renamed and pinned or something.

**Comment by tznind** [comment]
Closing as this as no complains in 20 days over the proposed solution of adding the patch info to the changelog.  There was a database patch in version 7.0.5 which can be seen below

![image](https://user-images.githubusercontent.com/31306100/151350134-7814b825-3e79-46af-9fc3-9d2472954540.png)
