### ISSUE TITLE
Date order isn't consistent for ViewLoads on dataload

### ISSUE THREAD

**Issue by RoyMudie** [HicServices/RDMP#902]
**Describe the bug**
When viewing the logs for a dataload (Right click on a data load -> view logs) the order appears to be in decending date order:
![image](https://user-images.githubusercontent.com/5470814/150818601-75a946e7-b2ca-4f11-8e2a-af378081437e.png)
However, when you expand requests in any log item, they are in the reverse order:
![image](https://user-images.githubusercontent.com/5470814/150818721-19900201-38ed-4823-b518-07433503352a.png)

**Expected behavior**
The date ordering should be consistant.

**Comment by tznind** [comment]
To me it is consistent.  You want to see the loads with the latest load of the dataset at the top so you don't have to scroll.  But when drilling down into a given load you want to see the order things happened in that load chronologically as they happened (not in reverse order).

**Comment by RoyMudie** [comment]
I think they're only correct because it's what you expect. I often get confused as to when things are ordered by date Descending or Ascending in RDMP and this specific view that has both orders in the same panel highlights how unclear that might be for the user.

I think it can be extra confusing to understand what order it's being displayed because some operations (like the example above) happen within the same second - so it's possible that you have to look down through quite a lot of items in a list to double check if you're looking at the last or first operation that happened.

I persoanlly feal like all operation lists/date columns should be ordered most recent at the top - and you need to scroll down to see past events.

In the example above, as you suggest, you want to see the "last dataload", so why wouldn't you want to see the "last operation" that succeeded/failed in that dataload when expanding it?
