### ISSUE TITLE
New Cohort Builder Query process

### ISSUE THREAD

**Issue by RoyMudie** [HicServices/RDMP#982]
**Creating a new Cohort Builder Query**

- [x] From project new menu, a new Cohort Builder Query should ask what project it is going to be added to
- [x] Update Title bar of Cohort Query Name to “New Cohort Builder Query”
- [x] Update “Cohort Name” to “Cohort Builder Query Name”

**When building a query**
- [x] Warning for "SET containers cannot be empty" and "SET container operations have no effect if there is only one child within." should include message to inform user: "Either Add a Catalogue or Disable/Delete this container if not required"
- [x] Double clicking a empty SET should fire "ExecuteCommandAddCatalogueToCohortIdentificationSetContainer" event.
- [x] _ExecuteCommandAddCatalogueToCohortIdentificationSetContainer_ as well as the ones associated for adding Aggregate, Existing Cohort Set and Existing Cohort Builder Query needs a description along the lines of "Select the Catalogue to Add to this Container"

**Committing a Cohort**
- [x] Update title description from "This form lets you describe the cohort you are trying to import" to something more meaningul.
- [x] Remove "doesn't exist yet" message

**Comment by tznind** [comment]
This is happening on branch `cohort-builder-process`

**Comment by tznind** [comment]
I've removed some of the original requirements of this ticket into
#989  and #998
