### ISSUE TITLE
Create Extraction Configuration workflow improvements

### ISSUE THREAD

**Issue by RoyMudie** [HicServices/RDMP#983]
Creating a new extraction configuration
 - [x] RDMP should automatically ask for Extraction Name
 - [x] Auto-populate  Extraction Name with "PROJ_NUMBER YYYY/MM Extraction"
 - [x] RDMP should ask for datasets to be added to extraction (can be skipped)
 - [x] RDMP should then ask for saved cohorts to be added to the extraction (can be skipped)

**Comment by tznind** [comment]
Removed everything that isn't specifically about creating new extractions into a seperate ticket (#1058)
